require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'SequelExample' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  pod 'react-native-quick-sqlite', :path => '../..'

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
