require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
	if linkage != nil
	  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
	  use_frameworks! :linkage => linkage.to_sym
	end

target 'QuickSQLiteExample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-quick-sqlite', :path => '../..'

  target 'QuickSQLiteExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    PLIST_BUDDY_PATH = '/usr/libexec/PlistBuddy'
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == "hermes-engine"
          installer.pods_project.files.each do |fileref|
            if fileref.path.end_with? "hermes.xcframework"
              hermes_plist_file = "#{fileref.real_path}/Info.plist"
              # Patch Hermes to remove the debug symbols entry from the Info.plist (as it's not shipped with it)
              # This might be removed once Hermes starts to ship with Debug symbols or we remove our
              # direct dependency from the Main iOS target on "hermes.xcframework"
              Open3.capture3(PLIST_BUDDY_PATH, '-c', 'Delete :AvailableLibraries:0:DebugSymbolsPath', hermes_plist_file)
              Open3.capture3(PLIST_BUDDY_PATH, '-c', 'Delete :AvailableLibraries:1:DebugSymbolsPath', hermes_plist_file)
              Open3.capture3(PLIST_BUDDY_PATH, '-c', 'Delete :AvailableLibraries:2:DebugSymbolsPath', hermes_plist_file)
            end
          end
        end
      end
    end

  end

end
